# Generated by Django 5.2.5 on 2025-08-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_descripcion'),
        ('categorias', '0001_initial'),
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categorias.categoria'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estados.estadoarticulo'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='EstadoArticulo',
        ),
    ]
