# Generated by Django 5.2.5 on 2025-08-12 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0003_alter_articulo_categoria_alter_articulo_estado_and_more'),
        ('estados', '0002_estadointercambio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios', to='articulos.articulo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estados.estadointercambio')),
                ('ofertante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_ofertados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
