# Generated by Django 5.2.5 on 2025-08-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='fecha',
            field=models.DateField(),
        ),
    ]
